apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-report-server
  namespace: mobile-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allure-report-server
  template:
    metadata:
      labels:
        app: allure-report-server
    spec:
      containers:
      - name: allure
        image: qameta/allure-docker-service
        ports:
        - containerPort: 5050
        env:
        - name: CHECK_RESULTS_EVERY_SECONDS
          value: "30"
        - name: KEEP_HISTORY
          value: "true"
        - name: PROJECT_ID
          value: "mobile-android"
        volumeMounts:
        - name: allure-results
          mountPath: /app/projects/mobile-android/results
        - name: allure-reports
          mountPath: /app/projects/mobile-android/reports
      volumes:
      - name: allure-results
        persistentVolumeClaim:
          claimName: allure-pvc
      - name: allure-reports
        emptyDir: {}