apiVersion: v1
kind: Service
metadata:
  name: allure-report-service
  namespace: mobile-testing
spec:
  selector:
    app: allure-report-server
  ports:
  - port: 5050
    targetPort: 5050
    nodePort: 30050  # Add this line if you want NodePort
  type: NodePort     # Change from ClusterIP to NodePort if you want external access