apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-test-runner
  namespace: mobile-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-test-runner
  template:
    metadata:
      labels:
        app: mobile-test-runner
    spec:
      containers:
      - name: test-runner
        image: mobile-test-runner:latest
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
        volumeMounts:
        - name: allure-results
          mountPath: /app/allure-results
        - name: test-source
          mountPath: /app/allureReport
      volumes:
      - name: allure-results
        persistentVolumeClaim:
          claimName: allure-pvc
      - name: test-source
        hostPath:
          path: /mobile-android-test/allureReport
          type: Directory