apiVersion: v1
kind: Service
metadata:
  name: mobile-test-service
  namespace: mobile-testing
spec:
  selector:
    app: mobile-test-runner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080